import argparse
import json
from pathlib import Path

import httpx

from master.config import load_settings
from shared.contracts import TaskEnqueueItem, TaskEnqueueRequest


def normalize_legacy_task(task: dict) -> TaskEnqueueItem:
    return TaskEnqueueItem(
        task_key=task.get("task_key", task.get("hash_id")),
        target_url=task["target_url"],
        task_type=task.get("task_type", task.get("type", "text_search")),
        search_keyword=task.get("search_keyword", task.get("Search_Keyword", "")),
        search_location=task.get("search_location", task.get("Search_Location", "")),
        order_id=task.get("order_id", ""),
        query_type=task.get("query_type", "Unknown"),
        minimum_reviews=task.get("minimum_reviews", 0),
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Enqueue task tickets generated by Master_Controller.py"
    )
    parser.add_argument("ticket", type=Path, help="JSON ticket containing a tasks list")
    args = parser.parse_args()
    settings = load_settings()
    ticket_data = json.loads(args.ticket.read_text(encoding="utf-8"))
    raw_tasks = ticket_data if isinstance(ticket_data, list) else ticket_data.get("tasks")
    if not isinstance(raw_tasks, list):
        raise ValueError("ticket JSON must be a task list or contain a 'tasks' list")
    payload = TaskEnqueueRequest(
        tasks=[normalize_legacy_task(task) for task in raw_tasks]
    )
    with httpx.Client(
        base_url=settings.master_api_url,
        headers={"Authorization": f"Bearer {settings.auth_token}"},
        timeout=30,
    ) as client:
        response = client.post(
            "/api/v1/tasks/enqueue",
            json={"tasks": [task.dict() for task in payload.tasks]},
        )
        response.raise_for_status()
    result = response.json()
    print(
        f"Enqueued {result['inserted']} tasks "
        f"({result['duplicates']} already existed)."
    )


if __name__ == "__main__":
    main()
